user_homepage:
    path:     /
    defaults: { _controller: UserBundle:Default:index }
Page_Client:
    path:     /pageClient
    defaults: { _controller: UserBundle:Default:Client }

Page_Admin:
    path:     /admin
    defaults: { _controller: UserBundle:Default:Admin }

Page_Fornisseur:
    path:     /pageFournisseur
    defaults: { _controller: UserBundle:Default:Responsable }
